server:
  port: 8083
  ssl:
    key-store-password: techgeeknext123
    key-store: classpath:securitykeystore.p12
    key-store-type: PKCS12
    key-alias: techgeeknext-alias


spring:
  datasource:
    url: jdbc:mysql://localhost/SecuritySchema?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    platform: mysql
    initialization-mode: always

  # Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
  hibernate.ddl-auto: create-drop

